image: continuumio/anaconda3

before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes git
  - chmod +x ./base_script.sh

stages:
  - build

build:
  stage: build
  script:
    - ./base_script.sh
